export enum ModelType {
  APP = 'app',
  ARRAY = 'arr',
  CELL = 'cell',
  COLUMN = 'col',
  CONSTANT = 'const',
  CONSTRUCTOR = 'ctor',
  DICTIONARY = 'dict',
  DOCUMENT = 'doc',
  FORMULA_EXPRESSION = 'formula-expr',
  GRID = 'grid',
  GRID_COLUMN = 'gridcol',
  MODEL = 'model',
  ROW = 'row',
}